/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.controladorClientes;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import modelo.Clientes;

/**
 *
 * @author Lubin Reyes
 */
public class FRMCliente extends javax.swing.JInternalFrame {

    controladorClientes clienteController = new controladorClientes();

    /**
     * Creates new form FRMCliente
     */
    public FRMCliente() {
        initComponents();
        TXTIdCliente.setValue(0);
        TXTIdCliente.setVisible(false);
        limpiarFormulario();

    }

    private void limpiarFormulario() {
        TXTIdCliente.setValue(0);
        TXTNombreCliente.setText("Escriba Nombre");
        TXTDocumentoCliente.setText("Escriba Documento");
        TXTDireccionCliente.setText("Escriba Direccion");
        TXTCelularCliente.setText("Escriba celular");
        TXTBuscarCliente.setText("Escriba texto a buscar");
        BTNModificar.setEnabled(false);
        BTNEliminar.setEnabled(false);
        llenarTabla();
    }

    public void llenarTabla() {
        Clientes unCliente = new Clientes();
        DefaultTableModel tabla = (DefaultTableModel) TBLCliente.getModel();
        Iterator<Clientes> itCliente = unCliente.listar();
        Object[] filaCliente = new Object[TBLCliente.getColumnCount()];
        tabla.setRowCount(0);
        while (itCliente.hasNext()) {
            unCliente = itCliente.next();
            filaCliente[0] = unCliente.getIdCliente();
            filaCliente[1] = unCliente.getNombreCliente();
            filaCliente[2] = unCliente.getDocumentoCliente();
            filaCliente[3] = unCliente.getDireccionCliente();
            filaCliente[4] = unCliente.getCelularCliente();
            tabla.addRow(filaCliente);

        }

    }

    private Clientes obtenerCliente() {
        Clientes elCliente = new Clientes();
        elCliente.setIdCliente((Integer) TXTIdCliente.getValue());
        elCliente.setNombreCliente(TXTNombreCliente.getText());
        elCliente.setDocumentoCliente(TXTDocumentoCliente.getText());
        elCliente.setDireccionCliente(TXTDireccionCliente.getText());
        elCliente.setCelularCliente(TXTCelularCliente.getText());
        return elCliente;

    }

    private void llenarTablaConBusqueda(String busqueda) {
        Clientes unCliente = new Clientes();
        DefaultTableModel tabla = (DefaultTableModel) TBLCliente.getModel();
        Iterator<Clientes> itCliente = unCliente.buscar(busqueda);
        Object[] filaCliente = new Object[TBLCliente.getColumnCount()];
        tabla.setRowCount (0);
        while (itCliente.hasNext ()){
         unCliente =itCliente.next();
         filaCliente[0] = unCliente.getIdCliente();
         filaCliente[1] = unCliente.getNombreCliente();
         filaCliente[2] = unCliente.getDocumentoCliente();
         filaCliente[3] = unCliente.getDireccionCliente();
         filaCliente[4] = unCliente.getCelularCliente();
         ((DefaultTableModel)TBLCliente.getModel()).addRow(filaCliente);
         
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLNombre = new javax.swing.JLabel();
        BTNInsetar = new javax.swing.JButton();
        TXTNombreCliente = new javax.swing.JTextField();
        TXTIdCliente = new javax.swing.JSpinner();
        LBLDocumento = new javax.swing.JLabel();
        TXTDocumentoCliente = new javax.swing.JTextField();
        BTNModificar = new javax.swing.JButton();
        LBLDireccion = new javax.swing.JLabel();
        TXTDireccionCliente = new javax.swing.JTextField();
        BTNEliminar = new javax.swing.JButton();
        LBLCelular = new javax.swing.JLabel();
        TXTCelularCliente = new javax.swing.JTextField();
        BTNCerrar = new javax.swing.JButton();
        LBLBuscar = new javax.swing.JLabel();
        TXTBuscarCliente = new javax.swing.JTextField();
        BTNBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLCliente = new javax.swing.JTable();

        LBLNombre.setText("Nombre");

        BTNInsetar.setText("Insertar");
        BTNInsetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInsetarActionPerformed(evt);
            }
        });

        TXTNombreCliente.setText("Escriba su nombre");

        LBLDocumento.setText("Documento");

        TXTDocumentoCliente.setText("Escriba Documento");
        TXTDocumentoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDocumentoClienteActionPerformed(evt);
            }
        });

        BTNModificar.setText("Modificar");
        BTNModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarActionPerformed(evt);
            }
        });

        LBLDireccion.setText("Direccion");

        TXTDireccionCliente.setText("Escriba Direccion");
        TXTDireccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDireccionClienteActionPerformed(evt);
            }
        });

        BTNEliminar.setText("Eliminar");
        BTNEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminarActionPerformed(evt);
            }
        });

        LBLCelular.setText("Celular");

        TXTCelularCliente.setText("Escriba Celular");

        BTNCerrar.setText("Cerrar");
        BTNCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCerrarActionPerformed(evt);
            }
        });

        LBLBuscar.setText("Buscar");

        TXTBuscarCliente.setText("Escriba texto a buscar");
        TXTBuscarCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarClienteFocusGained(evt);
            }
        });
        TXTBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTBuscarClienteActionPerformed(evt);
            }
        });

        BTNBuscar.setText("Buscar");
        BTNBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BTNBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BTNBuscarFocusLost(evt);
            }
        });
        BTNBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarActionPerformed(evt);
            }
        });

        TBLCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Documento", "Direccion", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LBLDocumento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTDocumentoCliente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LBLNombre)
                                .addGap(18, 18, 18)
                                .addComponent(TXTNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(TXTIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLDireccion)
                            .addComponent(LBLCelular))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LBLBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TXTBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNInsetar)
                    .addComponent(BTNModificar)
                    .addComponent(BTNEliminar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BTNCerrar))
                    .addComponent(BTNBuscar))
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLNombre)
                    .addComponent(BTNInsetar)
                    .addComponent(TXTNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLDocumento)
                    .addComponent(TXTDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNModificar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLCelular)
                    .addComponent(TXTCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLBuscar)
                    .addComponent(TXTBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNInsetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInsetarActionPerformed
        clienteController.controlarAccion(evt, obtenerCliente());
        limpiarFormulario();
    }//GEN-LAST:event_BTNInsetarActionPerformed

    private void TXTDocumentoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDocumentoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDocumentoClienteActionPerformed

    private void BTNModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarActionPerformed
        clienteController.controlarAccion(evt, obtenerCliente());
        limpiarFormulario();// TODO add your handling code here:
    }//GEN-LAST:event_BTNModificarActionPerformed

    private void BTNBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarActionPerformed
        // TODO add your handling code here:
        llenarTablaConBusqueda(TXTBuscarCliente.getText());
    }//GEN-LAST:event_BTNBuscarActionPerformed

    private void BTNEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminarActionPerformed
        clienteController.controlarAccion(evt, obtenerCliente()); 
        llenarTabla();
// TODO add your handling code here:
    }//GEN-LAST:event_BTNEliminarActionPerformed

    private void BTNCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCerrarActionPerformed
        doDefaultCloseAction();        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCerrarActionPerformed

    private void TBLClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLClienteMouseClicked

        if (evt.getClickCount() == 2) {
            int fila = TBLCliente.rowAtPoint(evt.getPoint());
            if (fila > -1) {
                TXTIdCliente.setValue((Integer) TBLCliente.getValueAt(fila, 0));
                TXTNombreCliente.setText((String) TBLCliente.getValueAt(fila, 1));
                TXTDocumentoCliente.setText((String) TBLCliente.getValueAt(fila, 2));
                TXTDireccionCliente.setText((String) TBLCliente.getValueAt(fila, 3));
                TXTCelularCliente.setText((String) TBLCliente.getValueAt(fila, 4));
                BTNModificar.setEnabled(true);
                BTNEliminar.setEnabled(true);
                // TODO add your handling code here:
            }
        }
    }//GEN-LAST:event_TBLClienteMouseClicked

    private void TXTDireccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDireccionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDireccionClienteActionPerformed

    private void BTNBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BTNBuscarFocusGained
        if (TXTBuscarCliente.getText().equals("Escriba texto a buscar")) {
            TXTBuscarCliente.setText("");
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNBuscarFocusGained

    private void BTNBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BTNBuscarFocusLost
        // TODO add your handling code here:
        if (TXTBuscarCliente.getText().isEmpty()) {
            TXTBuscarCliente.setText("Escriba texto a buscar");
            
        }
    }//GEN-LAST:event_BTNBuscarFocusLost

    private void TXTBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTBuscarClienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TXTBuscarClienteActionPerformed

    private void TXTBuscarClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarClienteFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TXTBuscarClienteFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscar;
    private javax.swing.JButton BTNCerrar;
    private javax.swing.JButton BTNEliminar;
    private javax.swing.JButton BTNInsetar;
    private javax.swing.JButton BTNModificar;
    private javax.swing.JLabel LBLBuscar;
    private javax.swing.JLabel LBLCelular;
    private javax.swing.JLabel LBLDireccion;
    private javax.swing.JLabel LBLDocumento;
    private javax.swing.JLabel LBLNombre;
    private javax.swing.JTable TBLCliente;
    private javax.swing.JTextField TXTBuscarCliente;
    private javax.swing.JTextField TXTCelularCliente;
    private javax.swing.JTextField TXTDireccionCliente;
    private javax.swing.JTextField TXTDocumentoCliente;
    private javax.swing.JSpinner TXTIdCliente;
    private javax.swing.JTextField TXTNombreCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
